version: "3.2"
services:
  ports-service:
    image: ports-service:local-build
    container_name: ports-service
    ports:
      - 8081:8081
    environment:
      PORT: 8081

  ports-api:
    image: ports-api:local-build
    container_name: ports-api
    depends_on:
      - ports-service
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      PORTS_SERVICE_ENDPOINT: "ports-service:8081"